### ISSUE TITLE
Compilation error in custom functions due to conflict with DocumentSnapshot

### ISSUE THREAD

**Issue by PepeChuymx** [FlutterFlow/flutterflow-issues#6648]
### Can we access your project?

- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Description: Custom functions cannot be tested because DocumentSnapshot in the generated code is not properly parameterized. The compiler fails with the error: Type 'DocumentSnapshot' not found. To ensure compatibility with cloud_firestore version ^5.x, the correct usage should be DocumentSnapshot<Map<String, dynamic>>.

### Expected Behavior

I’m creating simple custom functions in FlutterFlow (such as getEndOfDay and limpiarTextoGratitud) that do not depend on Firebase. However, when saving and testing these functions, FlutterFlow automatically adds imports like backend.dart and cloud_firestore, which causes compilation errors if DocumentSnapshot is not properly referenced in the generated models. This prevents testing functions that should compile without issue. It would be ideal if FlutterFlow allowed custom functions to compile in isolation, without automatically importing backend.dart when it’s not needed. Thank you for reviewing this case.

### Steps to Reproduce

Steps to Reproduce:
1. Create a simple custom function (e.g., getEndOfDay)
2. Save and compile
3. Run the Test Function
4. Compilation fails with: DocumentSnapshot isn't a type

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oiMn134pNrt8B7r6JK+5GiSQRHHo6ar8RicpBazwbfe+uB4kqevfOTERtUsumS2w3eGGGp2oW086MuN7LN/oEBxaZboM7/5BucT3hVkylWqaQFJWgYnF6I+RYC37A3MPUhR1/KulfW1IA62ayJ9ytdA/XJ4DSPmsSDa/LZO4=

### Visual documentation

<img width="868" height="517" alt="Image" src="https://github.com/user-attachments/assets/f3aaae6a-f28d-45eb-98eb-ed7818971929" />

<img width="1012" height="518" alt="Image" src="https://github.com/user-attachments/assets/53630e3f-6f33-4269-bc50-da9575bb8793" />

### Environment

```markdown
FlutterFlow v6.3.41 released Octuber 7, 2025.
Flutter version is 3.32.4
Platform: Web
Google Chrome. Versión 140.0.7339.185 (Build oficial) (64 bits)
Windows 10 Version 22H2 para x64 (KB5066747)

Environment: FlutterFlow Web cloud_firestore version: 5.6.9. Active Firebase collections
```

**Comment by Andresdiaz16** [comment]
can confirm this is happening on my side too.

**Comment by Juansarmi** [comment]
Hi! Sorry to hear you're experiencing this issue.

Unfortunately, I'm not able to reproduce the error on my end. It might be something specific to your project.

In this case, I recommend reaching out to support via the in-app chat or by email at [support@flutterflow.io](mailto:support@flutterflow.io) . They have the tools and access needed to take a closer look at your specific case.

Best regards.
